In [1]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


c:\Users\prash\anaconda3\envs\CIFAR\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
print(torch.__version__)
!nvidia-smi

1.11.0+cu113
Thu Aug  4 03:07:14 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 472.12       Driver Version: 472.12       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A    0C    P8     8W /  N/A |    134MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                           

### Introduction to Tensors
#### Creating Tesnsors




In [3]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
#vector 
vector = torch.tensor([2,2])
vector


tensor([2, 2])

In [7]:
vector.ndim

1

In [8]:
# Matrix 
matrix = torch.tensor([[7, 8],
                        [9,10]])
                
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
#tensor 
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

In [10]:
tensor.ndim

3

In [11]:
tensor.shape #this [1,3,3] means that we got one (3,3) Tensor

torch.Size([1, 3, 3])

In [12]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tesnsors
 
Why random Tensors ?

Random tesnsors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

start with random numbers > look at the data > update the random numbers > look at the data > update the random numbers 


In [13]:
# create the random tensors
random_tensors = torch.randn(3,4)
random_tensors

tensor([[-0.9557,  0.9599,  1.3847,  1.9305],
        [ 0.1790, -1.2832, -2.2751, -0.9468],
        [-0.0841,  0.9689,  0.4501,  0.0348]])

In [14]:
random_tensors.ndim

2

In [15]:
# Creat e a random tensor with similar shape to an image tensor 
Image_tensor  = torch.randn(248,248,3)

In [16]:
Image_tensor.ndim

3

In [17]:
# Zeros and Ones 
# Create a tensor of all zeros 
zeros  = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [18]:
# Create all ones 
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [19]:
ones.dtype

torch.float32

In [20]:
# Create a range of tensor 
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
one_to_1000 = torch.arange(start = 1, end = 1000, step = 77)

In [22]:
one_to_1000

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

### Tensor datatypes
**Note:** Tensor dataypes is one of the 3 big errors you'll run into with the PyTorch & deep learning:
1. Tensors not right datatype 
2. Tensors not right shape 
3. Tensors not on the right device 

In [23]:
# Tensor Datatypes  # single precision floating point is called float32 usually occupying 32 bits, float16 is the half precision
float_32_tensor = torch.tensor([3.0, 4.0, 5.0], 
                                dtype= None, 
                                device = None,
                                requires_grad= False)  # even if you specify dtype as None torch will have default as float 32
float_32_tensor.dtype

torch.float32

In [24]:
torch_16_tensor = float_32_tensor.type(torch.half)

In [25]:
torch_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [26]:
int_32_tensor = torch.tensor([[2,3],
                            [5,6]],device = 'cuda',
                             dtype = torch.long)

int_32_tensor.dtype

torch.int64

In [27]:
int_32_tensor.device

device(type='cuda', index=0)

### Getting information from Tensor

1. Tensors not right datatype - to get the datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get any shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get the device from a tensor, can use tensor.device

In [28]:
int_32_tensor.device, int_32_tensor.dtype, int_32_tensor.shape


(device(type='cuda', index=0), torch.int64, torch.Size([2, 2]))

In [29]:
x = torch.arange(1, 100, 10)

In [30]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [31]:
x.min()

tensor(1)

In [32]:
x.max()

tensor(91)

In [33]:
x.type(torch.float32).mean() #torch.mean function requires a tensor of float32

tensor(46.)

#### Reshaping, stacking, squeezing, unsqueezing 

* Reshaping - Reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor 
* Stacking - combine multiple tensors on the top of each other (vstack)  or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tesnor 
* Unsqueeze - add a `1`dimension to a target tensor 
* Permute  - Return a view of the input with the dimensions permuted (swapped) in a certain way


In [34]:
z = torch.arange(1., 10.)
z, z.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [35]:
# Add an extra dimension 
z_reshaped = z.reshape(3,3)

In [36]:
z_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [37]:
# Change the view 
y = z.view(3,3)
y, y.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [38]:
# Changing y changes z ( because a view of a tensor shares the same memory as the original input)
y[:]= 9
z,y

(tensor([9., 9., 9., 9., 9., 9., 9., 9., 9.]),
 tensor([[9., 9., 9.],
         [9., 9., 9.],
         [9., 9., 9.]]))

In [39]:
# Stack tensors on top of each other 
z_stacked = torch.stack([z,z,z], dim = 1)
z_stacked

tensor([[9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.]])

In [40]:
vstack = torch.vstack([z,z,z])
vstack


tensor([[9., 9., 9., 9., 9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [41]:
hstack = torch.hstack([z,z,z])
hstack

tensor([9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9.,
        9., 9., 9., 9., 9., 9., 9., 9., 9.])

In [42]:
zeros = torch.zeros(1,2,1,2)
zeros.dtype

torch.float32

In [43]:
o= zeros.squeeze() # Removes all single dimensions from a tesnors 

In [44]:
o.size()

torch.Size([2, 2])

In [45]:
print(f"this is the matrix after horizontal stacking {(hstack)} ")

this is the matrix after horizontal stacking tensor([9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9.,
        9., 9., 9., 9., 9., 9., 9., 9., 9.]) 


In [46]:
tensor = torch.ones(1,9)

In [47]:
tensor.shape

torch.Size([1, 9])

In [48]:
squeezed = torch.squeeze(tensor)
squeezed.shape

torch.Size([9])

In [49]:
squeezed.unsqueeze(dim =0).shape

torch.Size([1, 9])

In [50]:
# torch.permute changes the dimesnions of a targer tensor in a specified order
x_original = torch.randn(size = (224, 224, 3)) # Height, width , color channel
x_original.shape

torch.Size([224, 224, 3])

In [51]:
# Permute the original tensor to rearrange the axis or dimension order
x_permuted = torch.permute(x_original, (2,0,1)) # colour channel, height, width

In [52]:
# It shares the same space in the memory as of the original tensor just like as of view
print(f"previous shape {x_original.shape}")
print(f"New shape {x_permuted.shape}")

previous shape torch.Size([224, 224, 3])
New shape torch.Size([3, 224, 224])


## Indexing (selecting data from the tensor)

Indexing with Pytorch is similar to indexing with NumPy


In [53]:
y = torch.arange(1,10).reshape(1,3,3)
y, y.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [54]:
# Let's index on our new tensor 
y[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [55]:
y[0][0][1]  # first "[]" is for choosing the tensor, since now you have selected the tensor, second "[]" is for choosing the rows and third is for chosing the element from that row 

tensor(2)

In [56]:
y_new = y.reshape(1,1,3,3)

In [57]:
y_new.shape

torch.Size([1, 1, 3, 3])

In [58]:
y_new[0][0][0][2]

tensor(3)

In [59]:
y[:,:,2] #first electing the tensor than selecting the all the elements of that tensor by specfying the no. of rows than which element from cloumns

tensor([[3, 6, 9]])

In [60]:
print("the element from the tensor without square bracket", y[0][1][1])
print("the element from the tensor with square bracket", y[:,1,1]) #Because we are selecting all the values of the zero dimenions

the element from the tensor without square bracket tensor(5)
the element from the tensor with square bracket tensor([5])


In [61]:
import numpy as np

PyTorch and NumPy

* Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)

* PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [62]:
array = np.arange(1.0, 8.0)

tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [63]:
array.dtype

dtype('float64')

In [64]:
torch.arange(1.0, 8.0).dtype  # WARNING: torch has default datatype of float16 but while converting from numpy to tensor it gets float64

torch.float32

In [65]:
# Change the value of the array, what will this do to tensor?
array = array + 1

In [66]:
array, tensor  # NOTE : if You change the value of array it won't change the value of the tensor 

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [67]:
# Tensor to NumPy 
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [68]:
# change the tesnor, what will happen to numpy_tensor?
tensor = tensor + 1 
tensor, numpy_tensor    # it wont change the array, so this means they dont share the memory

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility ( trying to take random out of random)

In short how a neural 