In [2]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [3]:
print(torch.__version__)
!nvidia-smi

1.12.0
Fri Jul 29 02:49:53 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 472.12       Driver Version: 472.12       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A    0C    P8     7W /  N/A |    134MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+

### Introduction to Tensors
#### Creating Tesnsors




In [4]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
#vector 
vector = torch.tensor([2,2])
vector


tensor([2, 2])

In [8]:
vector.ndim

1

In [9]:
# Matrix 
matrix = torch.tensor([[7, 8],
                        [9,10]])
                
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
#tensor 
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

In [11]:
tensor.ndim

3

In [12]:
tensor.shape #this [1,3,3] means that we got one (3,3) Tensor

torch.Size([1, 3, 3])

In [13]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tesnsors
 
Why random Tensors ?

Random tesnsors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

start with random numbers > look at the data > update the random numbers > look at the data > update the random numbers 


In [14]:
# create the random tensors
random_tensors = torch.randn(3,4)
random_tensors

tensor([[-1.7058,  0.2888, -0.8965,  1.5803],
        [ 0.4828, -0.7003,  2.4300, -0.4597],
        [-1.1397, -0.9013,  1.5565,  1.6798]])

In [15]:
random_tensors.ndim

2

In [16]:
# Creat e a random tensor with similar shape to an image tensor 
Image_tensor  = torch.randn(248,248,3)

In [17]:
Image_tensor.ndim

3

In [18]:
# Zeros and Ones 
# Create a tensor of all zeros 
zeros  = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [19]:
# Create all ones 
ones = torch.ones(3,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

In [21]:
# Create a range of tensor 
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
one_to_1000 = torch.arange(start = 1, end = 1000, step = 77)

In [23]:
one_to_1000

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

### Tensor datatypes
**Note:** Tensor dataypes is one of the 3 big errors you'll run into with the PyTorch & deep learning:
1. Tensors not right datatype 
2. Tensors not right shape 
3. Tensors not on the right device 

In [24]:
# Tensor Datatypes  # single precision floating point is called float32 usually occupying 32 bits, float16 is the half precision
float_32_tensor = torch.tensor([3.0, 4.0, 5.0], 
                                dtype= None, 
                                device = None,
                                requires_grad= False)  # even if you specify dtype as None torch will have default as float 32
float_32_tensor.dtype

torch.float32

In [25]:
torch_16_tensor = float_32_tensor.type(torch.half)

In [26]:
torch_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [34]:
int_32_tensor = torch.tensor([[2,3],
                            [5,6]],device = 'cuda',
                             dtype = torch.long)

int_32_tensor.dtype

torch.int64

In [38]:
int_32_tensor.device

device(type='cuda', index=0)

### Getting information from Tensor

1. Tensors not right datatype - to get the datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get any shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get the device from a tensor, can use tensor.device

In [44]:
int_32_tensor.device, int_32_tensor.dtype, int_32_tensor.shape


(device(type='cuda', index=0), torch.int64, torch.Size([2, 2]))

In [45]:
x = torch.arange(1, 100, 10)

In [46]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [47]:
x.min()

tensor(1)

In [48]:
x.max()

tensor(91)

In [50]:
x.type(torch.float32).mean() #torch.mean function requires a tensor of float32

tensor(46.)

#### Reshaping, stacking, squeezing, unsqueezing 

* Reshaping - Reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor 
* Stacking - combine multiple tensors on the top of each other (vstack)  or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tesnor 
* Unsqueeze - add a `1`dimension to a target tensor 
* Permute  - Return a view of the input with the dimensions permuted (swapped) in a certain way


In [63]:
z = torch.arange(1., 10.)
z, z.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [52]:
# Add an extra dimension 
z_reshaped = z.reshape(3,3)

In [53]:
z_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [58]:
# Change the view 
y = z.view(3,3)
y, y.shape

(tensor([[5., 5., 5.],
         [5., 5., 5.],
         [5., 5., 5.]]),
 torch.Size([3, 3]))

In [61]:
# Changing y changes z ( because a view of a tensor shares the same memory as the original input)
y[:]= 9
z,y

(tensor([9., 9., 9., 9., 9., 9., 9., 9., 9.]),
 tensor([[9., 9., 9.],
         [9., 9., 9.],
         [9., 9., 9.]]))

In [70]:
# Stack tensors on top of each other 
z_stacked = torch.stack([z,z,z,z], dim = 0)
z_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [78]:
zeros = torch.zeros(1,2,1,2)
zeros

tensor([[[[0., 0.]],

         [[0., 0.]]]])

In [81]:
o= zeros.squeeze()

In [82]:
o.size()

torch.Size([2, 2])