In [7]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [9]:
print(torch.__version__)
!nvidia-smi

1.12.0
Wed Jul 27 03:28:06 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 472.12       Driver Version: 472.12       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   45C    P8     4W /  N/A |    134MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+

### Introduction to Tensors
#### Creating Tesnsors




In [12]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [13]:
scalar.ndim

0

In [14]:
scalar.item()

7

In [16]:
#vector 
vector = torch.tensor([2,2])
vector


1

In [17]:
vector.ndim

1

In [20]:
# Matrix 
matrix = torch.tensor([[7, 8],
                        [9,10]])
                
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [22]:
#tensor 
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

In [23]:
tensor.ndim

3

In [26]:
tensor.shape #this [1,3,3] means that we got one (3,3) Tensor

torch.Size([1, 3, 3])

In [27]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tesnsors
 
Why random Tensors ?

Random tesnsors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

start with random numbers > look at the data > update the random numbers > look at the data > update the random numbers 


In [28]:
# create the random tensors
random_tensors = torch.randn(3,4)
random_tensors

tensor([[ 0.0290, -0.1835,  0.4518,  0.6684],
        [-2.2689, -1.0504,  0.4853, -0.6974],
        [-1.5034,  0.4762, -0.5772, -0.7087]])

In [29]:
random_tensors.ndim

2